# Generated by Django 5.2.4 on 2025-07-22 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('identyfikator', models.CharField(blank=True, editable=False, max_length=4, null=True, unique=True)),
                ('tytul', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('miejsce', models.CharField(max_length=200)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Otwarte'), ('in_progress', 'W toku'), ('closed', 'Zamknięte')], default='open', max_length=20)),
                ('komentarz', models.TextField(blank=True, null=True)),
                ('przypisany_uzytkownik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
